### ISSUE TITLE
uncaught exception: ParserError: invalid line (no token ";" or ":") 

### ISSUE THREAD

**Issue by keksl** [wernerjoss/grav-plugin-fullcalendar#11]
Hi,

thanks for the plugin.

unfortunately he doesn't want to read the ics-file.
the calender is shown but empty.
in the console i get the error:

![Unbenannt-1](https://user-images.githubusercontent.com/60845400/74102600-4921cd00-4b45-11ea-9b45-a535ece7dcb2.jpg)

The ics file is valid - says https://icalendar.org/validator.html.

can you tell me why the appointments aren't being posted?
i can also provide you the ics-file in a private session, maybe there is a problem in it which the validator did not notice.

**Comment by wernerjoss** [comment]
well, that looks like the ical parser chokes on some content of your ics file.
can you send this to info AT hoernerfranzracing.de via email ?

**Comment by keksl** [comment]
thank you werner, great support.
problem was recurring events in ical file BDAY=1MO

problem is solved in version 0.2.1.

**Comment by s1-ranjan** [comment]
Facing "ParserError" with devanagari script- Hindi (हंदी)

**Comment by wernerjoss** [comment]
hello Rai,
I have no clue what devanagari script is - does that do something in a Grav 
Installation ?

Am Montag, 28. Februar 2022, 15:41:12 CET schrieb Rai:
