### ISSUE TITLE
No Events Showing

### ISSUE THREAD

**Issue by bmherard** [wernerjoss/grav-plugin-fullcalendar#12]
I've looked at previous posts and can't figure out why I can't see my event's. I've tried storing an ICS file in user/data/calendar...no events, linked to an Google ICS calendar...nothing, same with Outlook link to ICS...nothing. Shortcode Core is installed. I prefer linking to a services like Google Calendar because it will be easy for my client to add events.

**Comment by bmherard** [comment]
> I've tried storing an ICS file in user/data/calendar...no events

Actually I got ICS file to work but Google and Outlook still aren't showing events

**Comment by wernerjoss** [comment]
most likely, this is a CORS issue - see [closed issue #6](https://github.com/wernerjoss/grav-plugin-fullcalendar/issues/6) - same goes for Outlook, presumably.
does that help ?

**Comment by awrog** [comment]
> > I've tried storing an ICS file in user/data/calendar...no events
> 
> Actually I got ICS file to work but Google and Outlook still aren't showing events

@bmherard May I ask, how did you get it to work?

**Comment by wernerjoss** [comment]
@awrog you still have problems with local ICS files in /user/data/calendars ?
if so, can you try to set verbose to true in line 7 of templates/partials/fullcalendar.html.twig,
then in your browser, look what is displayed in javascript console (hit F12 to get there) ?

**Comment by awrog** [comment]
@wernerjoss Very thankfull for your help.
shortcode in page:
```
[fullcalendar icsfile=Afspraak.ics][/fullcalendar]
```
error in console is: 
```
... 404 (Not Found) https://palxyzxyzxyz.nl/bewoner/ontmoetingen/user/data/calendars/Afspraak.ics
```
the ics-file is located in:
```
/domains/palxyzxyzxyz.nl/public_html/user/data/calendars
```

**Comment by wernerjoss** [comment]
hm, this looks like the javascript function getAbsolutePath() returns a wrong base URL for your Installation.
However, there is a workaround: just put the correct absolute URL to your ics file in the shortcode.
be sure this is the URL which lets you directly access (download) the ics file when used in a new browser window.

**Comment by awrog** [comment]
When using [fullcalendar icsfile=/user/data/calendars/Afspraak.ics][/fullcalendar]
the path just gets added extra and generates another 404
When I add a valid URL (https://www.pal....) I get blocked by CORS policy 

p.s.: GRAV 1.6.19 / PHP Version 7.2.27

**Comment by wernerjoss** [comment]
> When using [fullcalendar icsfile=/user/data/calendars/Afspraak.ics][/fullcalendar]
the path just gets added extra and generates another 404

well, that is how it is supposed to work - as said, normally getAbsolutePath() returns the base URL of your installation and then /user/data/calendars is added to build the full path to the local ics file.
if that does not work, either the returned base URL is wrong or the ics file is elsewhere.

> When I add a valid URL (https://www.pal....) I get blocked by CORS policy

CORS policy is usually only an issue when the URL points to another Domain than that of the script - is that true ?
and even if so, it can be circumvented by using a reverse proxy as outlined by flo-bananzki in [issue 6](https://github.com/wernerjoss/grav-plugin-fullcalendar/issues/6)

**Comment by Strixos** [comment]
Hey guys ! :)

I just tried to show events from Google Calendar but it didn't work. 
I use the URL of my ics Google Calendar (the link works) but there is no event in the calendar.

Even with the example.ics I don't see event.

Regards

**Comment by wernerjoss** [comment]
as already outlined in this same thread, this is a CORS issue, which can be resolved by using a CORS proxy.
I have now created a new version (0.2.2) which automatically adds a CORS proxy URL to remote Calendar File URLs - please download and report back here.

**Comment by Strixos** [comment]
Thanks it works now, I see my event from the Google Calendar.
You're pro ! 😄

**Comment by wernerjoss** [comment]
Ok, thats fine - I have now created a new release (v 0.2.2) which incorporates this feature.
I'm also closing this issue now.
P.S.:
if you like this plugin, you can give it a star :smile:

**Comment by awrog** [comment]
Fixed my [problem](https://github.com/wernerjoss/grav-plugin-fullcalendar/issues/3) too!
Thanx

**Comment by wernerjoss** [comment]
Ok, fine :smiley:
