### ISSUE TITLE
Grav Admin Panel Link

### ISSUE THREAD

**Issue by fugo** [wernerjoss/grav-plugin-fullcalendar#13]
Hi
only a small issue at the Grav Admin Panel Plugin Section.
The URL to the Github README.md is wrong. 
Instead of `https://github.com/wernerjoss/grav-plugin-fullcalendar/README.md`( -> 404 ) it should be `https://github.com/wernerjoss/grav-plugin-fullcalendar/` or to the .md file directly `https://github.com/wernerjoss/grav-plugin-fullcalendar/blob/master/README.md`

**Comment by wernerjoss** [comment]
Ok, fixed here ;-)
and thanks for reporting - I nearly never use the Grav Admin, so I missed that.
