### ISSUE TITLE
Google repeating event wrong day

### ISSUE THREAD

**Issue by fugo** [wernerjoss/grav-plugin-fullcalendar#14]
Now I have a strange behavior with google calendar.
If I use **repeating** event starting 2nd March - last day 9th March  
Fullcalendar shows 1st March to 8th March :roll_eyes:  
If I use event start point 2nd to end point 9th it works.

Google calendar is public and I use https://calendar.google.com/calendar/ical/XXXX%40gmail.com/public/basic.ics
I have own heroku revers proxy.

**Comment by wernerjoss** [comment]
did you check your RRULE strings working as expected [here](http://jakubroztocil.github.io/rrule/) ?

**Comment by fugo** [comment]
Google counts different ``RRULE:FREQ=DAILY;UNTIL=20200318`` by Google is 18th included.
I don't use repeating events by now. I can live with an event with a **starting day** ( 2.nd March) and an **end day** (17th March). This shows the same time period.
Thank you your plugin runs well. :+1:

**Comment by wernerjoss** [comment]
Ok, fine to read you got it sorted out :+1: 
thus, I'm going to close this issue now...
