### ISSUE TITLE
Resizing the calendar depending on the device

### ISSUE THREAD

**Issue by Strixos** [wernerjoss/grav-plugin-fullcalendar#15]
Hi wernerjoss,

I'd like to know if the calendar can be resized in some way in order to show it correctly regardless the device used ?

If yes, could you explain me how to do it ?

Thanks a lot, and I gave you a star for the last time 😄

**Comment by wernerjoss** [comment]
@Strixos ,
the calendar can be resized easily as it is contained in its own container, the ID is #calendar .
if you like to do this depending on the device, you should use [media querys](https://www.w3schools.com/css/css_rwd_mediaqueries.asp) in the corresponding css.
the plugin comes with its own daygrid.css under assets, which just does what I need for my own calendar - feel free to add your own css as you like it, you can always experiment directly in your browser's development console, usually invoked by hit F12.
but be aware that if you change the provided daygrid.css, this might be overwritten by an update.
better option is to add everything to the custom.css file from your theme as this will be preserved.
I'm closing this now, as styling/css is not a plugin issue, but belongs to design/Themeing.

and yes, I saw your star - thanks :smile:
