### ISSUE TITLE
ICS file not appearing

### ISSUE THREAD

**Issue by CameronLiddell** [wernerjoss/grav-plugin-fullcalendar#2]
Calendar is showing but the ICS file is not being loaded.

I had to create the directory manually for the ics file to sit in (user/data/calendars). From there I am using the shortcode [fullcalendar icsfile=example.ics][/fullcalendar] (example.ics replaced with the name of my ics file).

This produces an empty calendar. Any thoughts on what I might be missing?

**Comment by awrog** [comment]
I'm having the same issue.
New GRAV install (1.6.9)
demo-ical file attached.
[keulen.zip](https://github.com/wernerjoss/grav-plugin-fullcalendar/files/3202650/keulen.zip)

**Comment by wernerjoss** [comment]
please see my comments in previous issue w.r. plugin shortcode core.
does that help ?

**Comment by FabianClemenz** [comment]
got the same problem with a local ics file.

i have the page with the shortcode under /aktuelles/termine

and getAbsolutePath() always returns http://localhost:8000/aktuelles

which doesn't get me the ics file under http://localhost:8000/user/data/calendars/example.ics

maybe you should use just the `window.location.origin` ? For stacked sites (like mine) this would be necessary

**Comment by wernerjoss** [comment]
window.location.origin does not work, I just checked this out.
did you try to put your whole calendar URL in the shortcode ?
(that should work, as in this case, getAbsolutePath() is not used, just the URL, and as it is on localhost, CORS should not be an issue)

**Comment by FabianClemenz** [comment]
whole URL did work. 

and setting `origin + '/'` worked too for me. but i think the URL should be the way to go. Thanks!
