### ISSUE TITLE
deactivate background image?

### ISSUE THREAD

**Issue by fugo** [wernerjoss/grav-plugin-fullcalendar#20]
Fullcalender 0.2.4

I don't use images and so I get a icon/placeholder for missing image from the link to the background image.
`</p><div id="actMonth"><img `src="/information/Juli.jpg"></div>`
I made 12 1x1px white JPG but it would be cool to deactivate this in the Yaml file. :smirk:

**Comment by wernerjoss** [comment]
you are right - I didn't notice this as I use calendar images :smile:
please try the updated assets/monthpic.js file, this should fix the issue.
be sure to delete your 'fake pics' and clear the cache.

**Comment by fugo** [comment]
Thanks a lot, will try this 🙂

and it works :+1:
