### ISSUE TITLE
Event are shown as full day event when they're not

### ISSUE THREAD

**Issue by Strixos** [wernerjoss/grav-plugin-fullcalendar#21]
Hi,

I noticed that all event in the calendar are shown as a full day event whereas they are 2h event or less.

Here is the page with the calendar :
![image](https://user-images.githubusercontent.com/27220378/91588743-f11fac00-e958-11ea-9d3e-4104985ce703.png)

And this is the same calendar from Google : 
![image](https://user-images.githubusercontent.com/27220378/91588809-05fc3f80-e959-11ea-9e50-68fbab4e1f4d.png)

Is it a global issue to this plugin or I need to configure something ? I tried to find a display configuration with no success.

Thanks

**Comment by wernerjoss** [comment]
@Strixos : this is a css issue:
the default css for assets/daygrid.css is

`#calendar .fc-time {
	display: none;
}
`

if you change it to display: inline-block; it will look like [this demo](https://fullcalendar.io/docs/v4/event-colors-demo).
however, this could be overwritten again by an update.
so you're better off doing this in a custom css file from your theme.
HTH

**Comment by wernerjoss** [comment]
additional note: I realized that changing the css as proposed above does not work well for allDay events.
so I made some minor changes to reflect this, and no more css change necessary.
please try this new version and report if it works for you.

**Comment by Strixos** [comment]
Hi @wernerjoss,

It works, but there is something wrong with the time. The timezone is wrong with the locale "fr" and the events are 2h early.

![image](https://user-images.githubusercontent.com/27220378/91655501-39ea7880-eab1-11ea-9024-7e6927404839.png)

Do you think it will be possible to add in the fullcalendar.yaml a timezone setting ?

Thanks,

**Comment by wernerjoss** [comment]
hm,
normally it should work - my calendar entries with time look like this:

`DTSTART;TZID=Europe/Berlin:20190112T193000
`
can you attach an ics file with some of your entries that show time offset ?

**Comment by Strixos** [comment]
Here is the [link](https://outlook.live.com/owa/calendar/00000000-0000-0000-0000-000000000000/44316a8d-9721-41e6-9177-5dfc0371b47d/cid-A432B55193DE6319/calendar.ics) to download the ics file.

I have this in the ics file but it works with Google.
`DTSTART;TZID=W. Europe Standard Time:20200829T100000`

**Comment by wernerjoss** [comment]
well, I think I found the problem: it is with the used rrule.js Library, see [here](https://github.com/jakubroztocil/rrule#timezone-support) and effects only repeating events (time display for single events is ok).
I'll see if I can implement a time zone setting in the rrule part, but that might take some time :smile:

**Comment by Strixos** [comment]
Thanks for the information. I think I'll rollback to the previous version in order to let you work on that and remove the event start time on my website 😄

**Comment by wernerjoss** [comment]
ok - but you don't need to rollback and remove event start-times :smile: 
you need just to enable display:none; in assets/daygrid.css (commented out there, currently).

**Comment by wernerjoss** [comment]
after digging a bit further into this issue, it appears more and more weird...
so far, I have no clean solution.
but, as a temporary workaround, I have added a new config variable tz_offset.
in your case, update from master branch and set it to 2 (=2 hours) then your calendar should look ok :smile:

**Comment by wernerjoss** [comment]
additional note:
if you have only one calendar and don't need month pics and legends, you can also use this [https://github.com/sherpadawan/grav-plugin-fullcalendar](https://github.com/sherpadawan/grav-plugin-fullcalendar) fork, which already solves this issue and will eventually be merged in a future version.

**Comment by Strixos** [comment]
Hi,
I updated the plugin to the last version and set the tz_offset variable to 2 in the .yaml file.
Everything seems good 😄 

Edit 1 : I don't know if it's related. I think not but I updated the plugin and now all my forms doesn't work. I can't even log into Admin.
Edit 2 : Wasn't related to the update indeed, just a bad drag & drop of the Form folder into FullCalendar folder .. My bad

**Comment by wernerjoss** [comment]
ok, fine :)
but, as said, this is not a clean solution, just a workaround.
you may also need to adapt tz_offset when daylight saving time changes.
I'm closing this issue now as resolved (for now), looking forward to getting the fork from sherpadawan working with all remaining issues there.
but this will take some time...
