### ISSUE TITLE
Rendered Calendar Has No Events (Grav 1.7-rc16)

### ISSUE THREAD

**Issue by thekenshow** [wernerjoss/grav-plugin-fullcalendar#23]
I was able to install and get events listed with the icalendar plugin, but when I use the same local mail@myorg.ics file with FullCalendar, no events are shown. For example, the .ics contains the following event for September 25th:

```
BEGIN:VEVENT
DTSTART:20200925T230000Z
DTEND:20200926T010000Z
DTSTAMP:20200919T130926Z
UID:myuserid@google.com
CREATED:20200328T145807Z
DESCRIPTION:
LAST-MODIFIED:20200916T174536Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:Commons MyOrganization
TRANSP:OPAQUE
END:VEVENT
```

But the rendered calendar for that date is empty:

![Screen Shot 2020-09-19 at 9 22 43 AM](https://user-images.githubusercontent.com/998832/93668394-f9e83700-fa59-11ea-8ae6-833f75fc8f71.png)

**Comment by wernerjoss** [comment]
this is strange - I just created a test file with only your listed event, this is shown as expected.
can you check what is shown in the browser debug window (hit F12 to see it) ?

**Comment by wernerjoss** [comment]
additional note: which theme do you use ?
(that might be a reason why it does not work for you due to evtl. missing jquery asset - most grav themes come with jquery, but maybe some do not ?)

**Comment by thekenshow** [comment]
I'm using a RockeTheme/Gantry5 theme called Photon, which does have jQuery 2.x and that does exist on the page. 

I do see a `user/data/calendars/&:1 Failed to load resource: the server responded with a status of 404 (Not Found)` error (should've caught that, oops). Here's the shortcode for this - could the `@` be causing problems? 

```
[fullcalendar icsfile='mail@harmonycentreos.ca.ics'][/fullcalendar]
```

**Comment by wernerjoss** [comment]
ok, the 404 is at least a hint...
normally, the @ in the calendar file name should not be a problem, but to be sure: just try without that.
be sure to clear the cache after the change, thow.

**Comment by wernerjoss** [comment]
ah, I just noticed your shortcode syntax: can you replace the ' surrounding the file name with " (double quote) ?

**Comment by thekenshow** [comment]
The single quote was the issue; switched to " and it's rendering perfectly. Thanks!

**Comment by wernerjoss** [comment]
ok, fine :smile:  - I'm pretty sure it also used to work with single quotes, maybe this was due to an older jquery version.
I have now updated the docs with an extra hint, just in case anyone stumbles over this issue.
I'm closing this issue now - thanks for reporting !
