### ISSUE TITLE
Month name is missing

### ISSUE THREAD

**Issue by kostaskleas** [wernerjoss/grav-plugin-fullcalendar#27]
All of a sudden the name of the month displayed on my calendar page disappeared... When i try to test it on a new test-web site the month name is missing.. Am i doing something wrong?

**Comment by wernerjoss** [comment]
@kostaskleas : did you change any configuration before month name disappeared ? especially: locale setting in /config/plugins/fullcalendar.yaml ?

**Comment by wernerjoss** [comment]
closing because of OP inactivity.
