### ISSUE TITLE
'Week numbers' setting is ignored

### ISSUE THREAD

**Issue by lguariento** [wernerjoss/grav-plugin-fullcalendar#28]
Hello,

I have just installed version 0.2.6 of the plugin on Grav 1.7.7 and the 'show week numbers' setting is set to disabled. Nevertheless the week numbers are shown on the front-end.

**Comment by wernerjoss** [comment]
ok, I see you are right :smile: -
can you just replace the file assets/calendar.js with the new version from master and try again ?

**Comment by lguariento** [comment]
That's now fixed, thanks.
