### ISSUE TITLE
PopOver rendered in raw format

### ISSUE THREAD

**Issue by traumturbulenzen** [wernerjoss/grav-plugin-fullcalendar#29]
The popup window renders the content of the calendar entry in raw format. I would like it to be rendered in markdown.

![Screenshot from 2021-04-14 16-26-37](https://user-images.githubusercontent.com/18284142/114727298-61d7d500-9d3e-11eb-9732-33043fa4bfe5.png)

> Liebe Grüße aus der dreckigen Hauptstadt. Ansonsten «freshes» plugin. Die Lösung mit dem cronjob gefällt mir auch sehr.

**Comment by wernerjoss** [comment]
hi @traumturbulenzen ,
das Rendering des Popups wird durch tippy.js gemacht, momentan einfach nur indem dort der content referenziert wird, das ist bei mir hier immer einfacher Text 😄 .
man kann da aber auch Html zulassen, siehe [doku](https://atomiks.github.io/tippyjs/v6/html-content/).
ich würde einfach mal probieren, nach Zeile 120 in assets/calendar.js das hier:
`allowHTML: true`
einzufügen.

**Comment by wernerjoss** [comment]
ich hab das mal eingebaut, funktioniert hier mit html description und schadet ansonsten offenbar nicht :smile:

**Comment by traumturbulenzen** [comment]
Super Ding. So sollte das sein. Vielen Dank. 
Komm gut durch und bleib gesund.

**Comment by wernerjoss** [comment]
ok, prima, ebenso.
ich mach das dann hier zu.
btw., wenn dir das Plugin gefällt, kannst ihm einen Stern geben :smile:

**Comment by pamtbaau** [comment]
@wernerjoss, @traumturbulenzen, Please have the courtesy towards other community members to use the lingua franca of the internet: English.

**Comment by wernerjoss** [comment]
@pamtbaau , yes, I normally try to keep all in English :smile:  - although sometimes it is faster and easier if someone begins with my native language.
