### ISSUE TITLE
Calendar empty

### ISSUE THREAD

**Issue by awrog** [wernerjoss/grav-plugin-fullcalendar#3]
I'm having the same issue.
New GRAV install (1.6.9)
demo-ical file attached.
[keulen.zip](https://github.com/wernerjoss/grav-plugin-fullcalendar/files/3211497/keulen.zip)

p.s. it looks like locale 'de' is hardcoded

**Comment by wernerjoss** [comment]
please see my comments in issue #1 w.r. plugin shortcode core.
does that help ?
and no, plugin does not support locales, ATM, using 'de' as default.
lets see what I can do here...

**Comment by awrog** [comment]
shortcode-core is installed. The calendar remains empty

**Comment by awrog** [comment]
After all updates and following the instructions regarding the icalendar plugin this plugin is now working.
