### ISSUE TITLE
Calendar fails to render

### ISSUE THREAD

**Issue by key-notes** [wernerjoss/grav-plugin-fullcalendar#31]
I'm a new Grav user, though not new to flat file CMSs or to coding. The FullCalendar shortcode fails to render for my installation, despite having (I believe) carefully followed all the instructions.

My installation uses the Admin Panel, and the page on which I'm testing Full Calendar uses the Calendar display template.

I've tried these shortcodes: `[fullcalendar icsfile="myevents.ics"][/fullcalendar]` and `[fullcalendar][/fullcalendar]`

myevents.ics is stored correctly in /user/data/calendars, and the Icalendar plugin can successfully read and parse it (but only using the updated code `{{ eventlist()|raw }}`—not the code listed in that plugin's readme file, but only by adding `|raw`).

Also, I've uploaded an extra copy of events.ics directly to this page's folder just in case.

Here are the config data for this plugin:

```
enabled: '1'
weekNumbers: '0'
colors: #3a87ad
showlegend: false
cors_api_url:
```

Many thanks in advance for any assistance.

**Comment by wernerjoss** [comment]
hi @key-notes ,
did you validate your ics file at [ics validator](https://icalendar.org/validator.html) ?
what happens if you drop the ics file in your calendar page folder ? - still no render ?
if not, you can try to set verbose = true; in line 5 of assets/calendar.js and then look what is printed in the browsers javascript console, especially errors...

**Comment by key-notes** [comment]
Hi Werner, thanks for your reply. I just validated the .ics file and it returned "Success! No errors found."

The .ics file was already directly in the calendar page folder. There's also a copy in /user/data/calendars for testing.

Oh, the JavaScript console seems to have revealed the problem: jQuery isn't being loaded.

Also, the following URLs aren't getting loaded:

/user/plugins/fullcalendar/assets/popper.min.js.map
/user/plugins/fullcalendar/assets/tippy-bundle.umd.min.js.map
/user/plugins/fullcalendar/fc4/vendor/rrule.js.map

Currently I'm using the latest Typhoon theme. I guess this theme doesn't use jQuery then?

**Comment by wernerjoss** [comment]
ah, ok,
if jQuery isn't loaded, that is the problem - the plugin assumes that, as each theme I came across so far, loads jQuery...
so, you could just try to load jQuery in your theme (e.g. add a line
`{% do assets.addJs('jquery', 100) %}` in base.html.twig)
or directly in the plugin, function AddAssets() in file fullcalendar.php

**Comment by key-notes** [comment]
Thanks! This is already part of the addAssets() function in fullcalendar.php: `$assets->addJs('plugins://' . $this->name . '/assets/jquery.ajax-cross-origin.min.js', ['group' => 'bottom']);`

I therefore added `{% do assets.addJs('jquery', 100) %}` to the `<head>` of base.html.twig in the template, and now the calendar is displayed. However, the data don't seem to get parsed, as the entries are all blank. Any ideas?

**Comment by wernerjoss** [comment]
> Thanks! This is already part of the addAssets() function in fullcalendar.php: `$assets->addJs('plugins://' . $this->name . '/assets/jquery.ajax-cross-origin.min.js', ['group' => 'bottom']);`

no, this is not jquery, but a package that depends on jquery :smile: 

> I therefore added `{% do assets.addJs('jquery', 100) %}` to the `<head>` of base.html.twig in the template, and now the calendar is displayed. However, the data don't seem to get parsed, as the entries are all blank. Any ideas?

did you set verbose = true in calendar.js ?
if so, you should see the parsed calendar entries in the javascript console.
or, at least, what goes wrong...

**Comment by key-notes** [comment]
verbose = true. The console is returning 404 errors, notably for /user/data/calendars/myevents.ics, even though this exact file is in that location. (I checked and double-checked for any typos.) Hmm.

**Comment by key-notes** [comment]
This identical file (same filename and contents) has also been uploaded to the page's folder.

**Comment by wernerjoss** [comment]
strange - 404 means just: not found, so no wonder there are no parsed entrys.
do you also get 404's if you just use the
[fullcalendar][/fullcalendar] shortcode ? (ics file in page folder, page should be normal page, not modular page)

can you send me the ics file ?

**Comment by key-notes** [comment]
No idea why it would return 404 errors when the .ics files are clearly there. I'll email you the exact link and file so you can have a closer look.

**Comment by wernerjoss** [comment]
ok

**Comment by wernerjoss** [comment]
I'm closing this now as it turned out the problem was that jquery was not loaded.
this plugin, however, assumed this would be done by any theme, which is not true.
so, the next version, 0.2.10, is underway which fixes the issue with a config option - see the docs.
