### ISSUE TITLE
Calendar gone after update

### ISSUE THREAD

**Issue by fugo** [wernerjoss/grav-plugin-fullcalendar#35]
Today I updated a site from a well running `0.2.4 `version to the new `0.2.10` and the calender is gone.
I would be happy for any hint to fix this.

```markdown
[span id="kalender"]<a name="kalender"></a>
<br>
[fullcalendar icsfile="https://calendar.google.com/calendar/ical/haus.freistabl%40gmail.com/public/basic.ics"][/fullcalendar]

```
HTML source 

```html
<p><span id="kalender"   ></span><a name="kalender"></a>
--
  | <br>
  |  
  | <div id='calendar'></div>
  | <div id='legend'></div>
  |  
  | <div id='weeknums' style='display:none;'>1</div>
  | <div id='cfgFilestring' style='display:none;'>https://calendar.google.com/calendar/ical/haus.freistabl%40gmail.com/public/basic.ics</div>
  | <div id='BgColstring' style='display:none;'>tomato, cornflowerblue</div>
  | <div id='CorsUrl' style='display:none;'>https://aqueous-stream-30687.herokuapp.com/</div>
  | <div id='showlegend' style='display:none;'>0</div>
  | <div id='tzoffset' style='display:none;'></div>
  | </p>
```
I don’t see any calendar scripts.

**Comment by wernerjoss** [comment]
well, there have been substantial changes from v 0.2.4 to 0.2.10.
first, please check if your theme loads jquery (most themes do this, if not, just set addJquery: true config option).
next thing to check would be the CORS Url, you should delete this in most cases, see CORS issues in the README file.

**Comment by fugo** [comment]
I removed the CORS URL before and jquery is loaded but no calendar.js `…  /system/assets/jquery/jquery-2.x.min.js"></script>`

my fullcalendar.yaml file:

```yaml
enabled: '1'
colors: '#930606, #1daaf9'
locale: de
weekNumbers: '1'
showlegend: '0'
addJquery: '0'
```

any other ideas?
I use the „Big Picture“ theme https://github.com/tranduyhung/grav-theme-big-picture

**Comment by wernerjoss** [comment]
calendar.js is loaded by fullcalendar.php, but only when the page template 'calendar' is used for the page that displays the calendar.
are you sure you use this ?

**Comment by fugo** [comment]
I use calendar on a modular page without this template. Before it was working. I will look in your twig to see, what I need to copy.

**Comment by wernerjoss** [comment]
Am Donnerstag, 23. September 2021, 22:24:08 CEST schrieb fugo:
> I use calendar on a modular page without this template. Before it was
> working. I will look in your twig to see, what I need to copy.

ah, ok, in that case, you will just have to comment out the check for the 
calendar template in fullcalendar.php, like this:

//	if ($page->template() === 'calendar') {
		$this->addAssets();
//	}

- no need copy anaything from the template.
the check was introduced to not automatically load the whole javascript stuff 
upon plugin loading.

**Comment by fugo** [comment]
I did a downgrade to version 0.2.4. and it works.
Will not tough it. Grav and all other plugins are up to date.
Sorry :disappointed:

**Comment by wernerjoss** [comment]
well, you could at least try my suggestion, which is easy to do.
if it does not work, you can always revert to v 0.2.4.
if it works, I could make a new version which allows to override the default behavior via config option.
that would then be update-safe (as opposed to the quick hack mentioned above).

**Comment by wernerjoss** [comment]
FYI, there is now a new config Option useCustomPageTemplate that (if set to true) will load all assets also if another page template than calendar.html.twig is used.
please note, that in this case, some changes from calendar.html.twig may have to be copied to the actually used template anyway in order to have everything working as expected.
I am closing this issue now, feel free to comment again if there are any further problems.
