### ISSUE TITLE
fullcalendar.php line 37

### ISSUE THREAD

**Issue by rkl110** [wernerjoss/grav-plugin-fullcalendar#38]
When I load the plugin I get an error: $config not defined...

Whoops \ Exception \ ErrorException (E_NOTICE)
Undefined variable: config

```
#    if (($page->template() === 'calendar') ) {
if (($page->template() === 'calendar') || ($config['useCustomPageTemplate']))    {
            $this->addAssets();
        }
    }
```

I guess the error happens because of my custom template. I'm using gantry5 and hydrogen Template.

For myself I fixed it, by excluding config var.

**Comment by u-cav** [comment]
I can confirm this on Grav v1.7.24, quark theme. Pages created with the "Calendar" template are correctly displayed, every other page will result in the "config not defined" error.

**Comment by ghtmtt** [comment]
I think the problem can be solved by creating the `config` variable also within the `onPageInitialized` function:

```php
	public function onPageInitialized(Event $event)
	{
		/** @var Page */
		$page = $event['page'];
                /** @var Config */
                $config = $this->config->get('plugins.fullcalendar');

		if (($page->template() === 'calendar') || ($config['useCustomPageTemplate'])) {
			$this->addAssets();
		}
	}
```

**Comment by wernerjoss** [comment]
@ghtmtt - of course you are right with your proposed fix, thanks - I missed to test this use case :smile: 
the fix is now in git master.
@all : please check / confirm it works for all of you, I'll then make a new release.

**Comment by rkl110** [comment]
> 
> 
> @ALL : please check / confirm it works for all of you, I'll then make a new release.

Works for myself

**Comment by wernerjoss** [comment]
ok, thanks.
I think there is no need to wait for @u-cav to confirm, I'm sure it will, too.
creating a new release and closing this now.
