### ISSUE TITLE
Flag 'editable' should be accessible via admin

### ISSUE THREAD

**Issue by Frank-1964** [wernerjoss/grav-plugin-fullcalendar#39]
Hi there,

this is a hint for one of the next versions of this wonderful plugin:

The fullcalendar.io flag 'editable' should be accessible via the grav admin panel.

Best regards,
Frank

**Comment by wernerjoss** [comment]
Hi @Frank-1964 ,
I just checked this out at [the demo site](https://fullcalendar.io/docs/event-dragging-resizing-demo) and messed a bit around with this.
from what I saw, editable=true will enable dragging events around to other days, yes.
but on page refresh, or, switch to next month and then back again, the event is again in its original place (as suposed).
the same is true if I set editable=true in my docker test site, also when logged in as admin.
so, the question for me is: what is the benefit of this feature ?

**Comment by Frank-1964** [comment]
Hi @wernerjoss,
that is exact the point. I do not see any benefit also, so I have disabled this flag actually in the code.
Therefore it would be better to set the flag to false by default or, as I suggested, to make the flag adjustable in the admin area.

**Comment by wernerjoss** [comment]
hm, strange.
I just also set editable=false in the calendar.js code of my docker test site, but it has no effect: I still can drag events around to other days, but will not persist.
so I doubt if making this adjustable via admin will make sense at all ?
also note that the default value for editable is false anyway, see the [docs](https://fullcalendar.io/docs/v4/editable).

**Comment by wernerjoss** [comment]
as there seems to be no real use of this flag, I'm closing this issue now.
