### ISSUE TITLE
Wrong Language

### ISSUE THREAD

**Issue by oldmanumby** [wernerjoss/grav-plugin-fullcalendar#4]
How can I get the calendar to display in English? Seems to default to some foreign language.

Thanks!

**Comment by wernerjoss** [comment]
ok, you're right, plugin is in german and uses 'de' locale :)
I'll have a look at this...

**Comment by lvennard** [comment]
I was able to get mine to english.  Without looking to hard, it searches for a locale file, if you just delete the /user/plugins/fullcalendar/assets/dist/locale/de.js file, it then defaults to english (or your default?)

**Comment by wernerjoss** [comment]
Ok, you are right - I had zipped all locales that I didn't need in my local copy and forgot to unzip them in the github repo :)
fixed now.

**Comment by wernerjoss** [comment]
sorry, closed too early - unzipping locales was not enough :-/
had to add a fix in fullcalendar.php, too.
this is now together with a new faeture (remote ics files) in [remote_url branch](https://github.com/wernerjoss/grav-plugin-fullcalendar/tree/remote_url).
please check if this works for you.
