### ISSUE TITLE
Add default values in fullcalendar.yaml

### ISSUE THREAD

**Issue by pamtbaau** [wernerjoss/grav-plugin-fullcalendar#40]
Not everyone uses Admin to save the plugin's config blueprint, in which case config variables are not set.

Error will be thrown on line fullcalendar.php:38:
> Undefined index: useCustomPageTemplate
```
if (($page->template() === 'calendar') || ($config['useCustomPageTemplate'])) {
```

Two suggestions:
- Add defaults values in fullcalendar.yaml
- To prevent exceptions when user removes `useCustomPageTemplate`, add same default values when using $config->get(). Eg. 
  ```
  $this->config->get('plugins.fullcalendar.useCustomPageTemplate', false)
  ```

**Comment by wernerjoss** [comment]
ok, suggestions made and committed.
