### ISSUE TITLE
The docs are not clear about using calendar.md or using setting useCustomPageTemplate

### ISSUE THREAD

**Issue by pamtbaau** [wernerjoss/grav-plugin-fullcalendar#43]
A [topic on Discourse](https://discourse.getgrav.org/t/no-display-from-full-calendar-page/19165) has been created because the page containing the shortcode remains empty. People were not aware that the filename of the page should be *calendar.md* by default

One user discovered that setting `useCustomPageTemplate` made the page work...

**Comment by ghost** [comment]
I think the simplest solution is to make the selector name in the settings a little clearer. Maybe “Enable on all page templates” with hover help that says “If this setting is disabled the calendar will only be enabled on the calendar.md template”. Or something like that.

**Comment by pamtbaau** [comment]
Both the README and the help in Admin should be perfectly clear about the implications of the setting. Apart from that, I think, the setting should not exist in the first place ([See issue #45](https://github.com/wernerjoss/grav-plugin-fullcalendar/issues/45)).

#### Admin:
I think a simple help does not make it clear enough what the implications are of using this setting. It must be made very clear what the effects are on the entire site. The help should not only be shown on hover, but should be a longer and permanent comment below the field. See [Display Field](https://learn.getgrav.org/17/forms/forms/fields-available#display-field).

#### README
The docs could be improved too. If I may be frank, the docs are also lacking a bit of styling (as the code does), which doesn't help with legibility.

Here is a suggestion for the README:


## Usage

### Calendars: local and remote
#### Local calendar files
Calendar files can be stored in two places:
- In folder */user/data/calendars*. For example:
  ```
  user/data/calendars
  ├── events.ics
  └── holidays,ics
  ```
- In the folder of the page itself. For example:
  ```
  user/pages
  ├── 01.home
  ├── 02.typography
  └── 03.events
      ├── calendar.md
      ├── events.ics
      └── holidays.ics
  ```
#### Remote calendars
 Also remote calendars can be accessed.  A CORS proxy will be used to access remote files (see below)
  
### Creating a page
#### Using Admin
Create a new page and choose 'Calendar' from the dropdown of field 'Page Template' in the 'Add Page' modal form.

#### Manually
When creating a calendar page using the command line, or your favourite editor, you must name the page `calendar.md`

#### Adding the shortcode
After creating a page, add a shortcode anywhere in the content of the page. The syntax of the shortcode depends on the location of the calendar files.
- When the calendar files are stored in folder */user/data/calendars/*, the name of the file must be specified:
  ```
  [fullcalendar icsfile="events.ics,holdays.ics, ..." /]
  ```
- When the calendar files are stored in the same folder as the page, the name of the calendar files can be omitted.
  ```
  [fullcalendar /]
  ```
- When accessing remote calendars, an absolute Url should be used:
  ```
  [fullcalendar icsfile="https://domain/path/to/calendar" /]
  ```
  
  To find the correct absolute Url, see article [How to find the iCal address for a public Google calendar](https://grantwinney.com/how-to-find-the-ical-address-for-a-public-google-calendar/)

#### Pages with their own template
Sometimes, a calendar must be added to a page which requires its own template, like a modular page, or a blog page. In that case, the 'Calendar' template, or filename `calendar.md`,  cannot be used for the page. For this situation, configuration variable `useCustomPageTemplate` can be set to `true`. 

Warning: This causes a performance overhead. The plugin will need to search for the shortcode in each and every page in the site and will add approx. 15 extra assets to every page.

### Adding pictures as current month
> Add explanation why one would like to do that.

You can show a picture for the current month above the calendar widget.  
In the folder of the calendar page, add 12 image named 'January.jpg', 'February.jpg', ... , 'December.jpg'.  
(Note that the names of the images must match the names of the month according to your locale setting, so, for locale: de, use 'Januar.jpg' ...).

**Comment by wernerjoss** [comment]
docs are updated and adapted to latest changes, closing this now.
