### ISSUE TITLE
Add example for Google calendar to readme

### ISSUE THREAD

**Issue by ghost** [wernerjoss/grav-plugin-fullcalendar#46]
It might be good to add a section to the readme about setting up a Google calendar, since this would be a fairly common usage scenario. I was going to do a PR but couldn't work out how to add images. So here is my suggested new section:

## Google calendar example
One common usage case would be to link the Fullcalendar plugin to your Google calendar. The first step is to make your Google calendar public. To do this go to settings using the three dots at the end of your calendar name (hover to make them appear). 
![calendar1](https://user-images.githubusercontent.com/46998578/145481758-e7378864-285a-4168-815d-ae491e030b61.png)
Select "Settings and sharing". Scroll down the page and tick the box to "Make available to public".
![calendar2](https://user-images.githubusercontent.com/46998578/145481928-761df0c2-07dd-4c68-8793-924085af858a.png)
Now scroll to the bottom of that screen and find the "Public address in ical format". Copy that url.
![calendar3](https://user-images.githubusercontent.com/46998578/145482285-1226c7ff-8ccb-496b-afc9-7f5ea6770a62.png)
This address is used in the shortcode. For example:

`[fullcalendar icsfile="https://calendar.google.com/calendar/ical/xxxxxxxxx%40gmail.com/public/basic.ics"][/fullcalendar]`

Information from the Google calendar will now be displayed and will remain in sync with all changes.

**Comment by wernerjoss** [comment]
hi @simplycomputing ,
you are right with the idea that an explanation like shown here would be helpful for google calendars, but frankly, I doubt it is a good thing to directly add this to the readme, which will then get even bigger and less likely to be read in brief :smile: .
so, I have now copied your hint in a separate file ExternalCalendars.md and added a link to the readme.
I think this is now more convenient, plus, the additional File can now easily expanded with examples for other popular Calendars like NextCloud, OwnCloud, Mailbox.org etc... without expanding the readme.
what do you think about this ?

**Comment by ghost** [comment]
Excellent idea! I can do one for Fastmail as well.

**Comment by wernerjoss** [comment]
thanks, Alan, that's fine.
just make a PR to the file ExternalCalendars.md when you're done - this way you will also be added to the Contributors list of the Plugin :smile:
