### ISSUE TITLE
Unable to copy from the description of a meeting

### ISSUE THREAD

**Issue by counterpoint** [wernerjoss/grav-plugin-fullcalendar#47]
The description of a meeting may include something like a link to an online conference. The description is shown as a popup when the user mouses over the calendar entry. But moving the cursor to the description (which is outside the area of the entry) results in the description disappearing. It is thus impossible to copy the link. It would be very helpful if this did not happen, and also if links were shown as clickable links.

**Comment by wernerjoss** [comment]
hi @counterpoint ,
the popup handling is done by the included javascript tippy.js and hence cannot be changed easily.
as for a link inside a description, yes, it is unfortunate not to be able to click it.
but there is a better solution: Links are supposed to be put in the [ICS Property URL:](https://icalendar.org/New-Properties-for-iCalendar-RFC-7986/5-5-url-property.html) - if done this way in the calendar application, a click at the event in the fullcalendar plugin will go to the link destination.
however, be aware that not all calendar apps can set that Property.
