### ISSUE TITLE
Feature req.: display published ical url

### ISSUE THREAD

**Issue by awrog** [wernerjoss/grav-plugin-fullcalendar#5]
Nice plugin!
It would be of great added value if it could display online published calendars (e.g. google calendar: ```https://calendar.google.com/calendar/ical/myname%40myorganization.com/public/basic.ics```

**Comment by wernerjoss** [comment]
ok, I agree this makes sense to some users :)
I have created an experimental branch, currently the only changed file is [this](https://github.com/wernerjoss/grav-plugin-fullcalendar/blob/remote_url/templates/partials/fullcalendar.html.twig).
can you try if this works for you with just 1 (ONE) remote calendar ?
note that you will have to put your remote url in " signs in your shortcode like so:
`[fullcalendar icsfile="https://calendar.google.com/calendar/ical/myname%40myorganization.com/public/basic.ics"][/fullcalendar]
`

**Comment by wernerjoss** [comment]
additional note:
you can also mix remote calendar url's with local calendar files in the shortcode.
just make sure the whole icsfile string is enclosed with double qoutes (") like so:
`[fullcalendar icsfile="https://calendar.google.com/calendar/ical/myname%40myorganization.com/public/basic.ics,calendar.ics"][/fullcalendar]`

**Comment by wernerjoss** [comment]
please try latest version in [remote_url branch](https://github.com/wernerjoss/grav-plugin-fullcalendar/tree/remote_url)

**Comment by awrog** [comment]
Sorry for my late reply.
Tried 0.1.4
It looks like it's not compatible with Google's iCAL format. Both downloaded and URL.
Example attached.
When I add [this](https://github.com/wernerjoss/grav-plugin-fullcalendar/files/3457093/basic.zip) ics to a woking calendar, all other appointments from other ics-files are gone, the calendar is empty.
The same applies to the Google calendar URL

**Comment by wernerjoss** [comment]
ok, I tried your ics file.
Problem is, it has several lines which are too long and, even worse, are split with line feeds.
once corrected, it works here.
you can find the corrected file at [pastebin](https://pastebin.com/CtbPjqAa)
for debugging purpose, you can also change $verbose to true in file templates/partials/fullcalendar.html.twig
and then use your browsers debug window to inspect what's going on.

**Comment by awrog** [comment]
Great, thanks for clearing that up

**Comment by flo-bananzki** [comment]
Hello, Sorry for open it again.
But I want to ask if there is any solution to the line-feed problem?
I saw in your fullcalendar.html.twig script you are search for \n and replace them with \r\n.
Is it possible to eliminate the line-feeds and spaces, so no error occours?
I mean is it possible without manual correcting?
I struggle with the same problem like awrog

**Comment by wernerjoss** [comment]
hm,
I don't think an automatic resolution for the line feed problem is that easy.
could eventually be done by check each line if it begins with a valid ical tag, if not, join it to the line before or something like that.
but anyways, I don't think it is a mandatory task for a plugin like this to correct faulty ics files.
