### ISSUE TITLE
Plugin fails to read .ics files from non-root pages

### ISSUE THREAD

**Issue by s1-ranjan** [wernerjoss/grav-plugin-fullcalendar#50]
I tried to enable the calendar from a non-root page (i.e., on http://exemple.com/calendars/calendar-1) it failed to read the .ics file, when I tried to investigate it shows me a 404 error for the .ics file.

**Comment by wernerjoss** [comment]
normally, it should read calendar files from user/data/calendars - is your .ics file there ?
additionally, you can also just drop the .ics file into the calendar page folder and it should be picked up.
did you try this ?

**Comment by wernerjoss** [comment]
...I just checked the same scenario:
for non root pages you should indeed store the .ics file in the page folder and use this (empty) shortcode:
[fullcalendar][/fullcalendar]
also be sure to use the standard page template 'calendar'.
this should work.

**Comment by wernerjoss** [comment]
I have now fixed this issue, the plugin does now also find calendar files in standard location user/data/calendars for non-root calendar pages.
please check and report if it works for you.

**Comment by wernerjoss** [comment]
I'm closing this now due to lack of feedback
