### ISSUE TITLE
google-ics german Umlaut not converted 

### ISSUE THREAD

**Issue by dioridna** [wernerjoss/grav-plugin-fullcalendar#53]
Environment:
Grav v1.7.35
Quark 2.0.4
Plugin FullCalendar v0.3.2
On the page named “Kalender” with the “Calendar” template, I have successfully imported/subscribed to a Google calendar using the shortcode [fullcalendar icsfile=“https://calendar.google.com/calendar/ical/ehj19bp2ds0ki14vuj9salmsf8%40group.calendar.google.com/public/basic.ics”]
[/fullcalendar]. Unfortunately, the German umlauts are not converted. So far I have not found a solution. Can anyone help me?
https://heutschi-merz.ch/gravcms/kalender

**Comment by wernerjoss** [comment]
hi @dioridna ,
you are right, Umlauts are not handeled correctly with remote google calendars.
if you copy the mentioned ics file to your server, everything is ok, though.
so, this might be an issue with the built-in CORS proxy which is required to access remote calendars.
I'll have a closer look at this, but that might take a while.

**Comment by dioridna** [comment]
Besten Dank für den klärenden Eintrag. Genau, mit den herunter- und wieder
hochgeladenen ics-Files funktioniert alles bestens. Mangels strukturierter
Kenntnisse kann ich bei der Lösungsfindung leider nicht mithelfen. Dir viel
Erfolg und danke für das gelungene Plugin.
Liebe Grüsse aus der Schweiz
Andi

_______________________
A. Heutschi-Merz mobil

Werner Joss ***@***.***> schrieb am Sa., 27. Aug. 2022, 16:50:

**Comment by wernerjoss** [comment]
Hi Andi,
probier mal die aktuelle Version aus dem Repo - das sollte nun funktionieren (tut es hier mit deinem Google Testkalender).

**Comment by dioridna** [comment]
Funktioniert nun wie gewünscht. Besten Dank!

**Comment by wernerjoss** [comment]
ok, prima - dann schliesse ich das hier mal.
ein neues Release mache ich noch nicht sofort, will erst mal sehen ob ich issue #52 noch demnächst lösen kann,
dann passt das besser.
und wenn dir das Plugin gefällt, kannst ihm einen Stern geben :smile: .

**Comment by dioridna** [comment]
Hallo Werner
Das ging ja schnell! Funktioniert bestens!
Vielen Dank für deine prompte und erfolgreiche Intervention.
Liebe Grüsse
Andi

Am Do., 1. Sept. 2022 um 17:48 Uhr schrieb Werner Joss <
***@***.***>:

**Comment by Racketsportler** [comment]
@dioridna : ich habe genau dasselbe Problem, das Du hattest - Darstellung von Umlauten in Events aus Google-Kalendern. Um jetzt nicht @wernerjoss mit einem bereits gelösten Problem zu behelligen:
- ich hatte festgestellt, daß die Version des Plugins, das ich verwende, noch 0.3.2 ist
- leider weiß ich nicht, wie man das Plugin manuell updatet, also bin ich so vorgegangen:

1. ich habe den Inhalt des Ordners ./user/plugins/fullcalendar gelöscht
2. dann habe ich das Repository geklont ("git clone ...")
3. den Inhalt (bis auf ".git") des geklonten Repositories habe ich nach ./user/plugins/fullcalendar verschoben

Im Backend wird mir angezeigt, daß das Plugin nun in neuerer Version verwendet wird: "FullCalendar v0.3.4"

Ich benutze:
- Grav v1.7.40 mit Admin v1.10.40 mit einem Strato-Konto
- ein Skeleton namens "Gateway" und das darin enthaltene Theme gleichen Namens
- den Default-Kalender in einem frisch angelegten Google-Konto, dessen "öffentliche Adresse im iCal-Format" lautet: https://calendar.google.com/calendar/ical/tchalingen%40gmail.com/public/basic.ics

Auf einer Seite unter user/pages/02.kalender habe ich folgenden Inhalt eingebunden: [fullcalendar icsfile="https://calendar.google.com/calendar/ical/tchalingen%40gmail.com/public/basic.ics"][/fullcalendar]
Der Kalender wird korrekt angzeigt, aber ein Event mit Umlauten wird leider immer noch nicht "gescheit" angezeigt: http://herzigs.org/TC-HalingenAlt/kalender
Im Kalender habe ich testhalber ein Event am 30.04.2023 mit einem Umlaut versehen.

Was muß ich anders machen?

Danke im Voraus für Hinweise, wie ich nicht mit "manuellen Umlauten" ("ae", "oe", usw.) arbeiten muß.

**Comment by wernerjoss** [comment]
hi @Racketsportler ,
hast recht - im Grav Directory ist immer noch die v0.3.2 des Plugins - das muss ich mal updaten (d.h. ein neues Release veröffentlichen) :-)
und das mit dem Update von Hand hast du richtig gemacht, die v0.3.4 ist aktuell.
Und damit wird er Testevent am 30.4. hier richtig angezeigt:
![grafik](https://user-images.githubusercontent.com/36265757/227967247-9df94869-d87e-4b56-8e22-c6db3653fead.png)
und nochwas: freut mich dass da einer mal das 'monthpic' Feature des Kalenders verwendet !

**Comment by Racketsportler** [comment]
@wernerjoss : Hallo Werner

Erstmal vielen Dank für die schnelle Antwort - ich hatte eher angenommen, daß ich ein paar Tage warten werde. Sehr nett!
Das war jetzt leider Vorführeffekt. Ich habe drei Browser auf meiner Kiste - und im Chrome hat ein Strg-F5 nicht dazu geführt, daß die Umlaute richtig dargestellt werden. Der Firefox zeigt es tatsächlich korrekt an. Ich habe nicht damit gerechnet, daß der Chrome so hartnäckig dabei bleibt.

Die Monatsbilder sind eher Spielerei. Ich wollte es ausprobieren, und fand die Bilder schön. Sieht wirklich wie ein echter Kalender aus.

Ich weiß, ich sollte keine Abkürzungen nehmen, sondern erstmal alles an Doku, FAQs, Known Bugs etc. wälzen. Vieles habe ich schon gelesen. Aber ich frage einfach mal - wenn etwas aufwändig zu recherchieren / auszuprobieren, aber lösbar sein sollte, werde ich es schon finden.

Was ich noch erreichen möchte ist:
- bei den Events sollte die Anfangszeit im 24-Stundenformat dargestellt werden, also z.B. "13:00" - statt "1p". Der richtige Ort für die Einstellung wird wahrscheinlich die site.yaml ("dateformat") oder die system.yaml sein. Leider hat es keinen Effekt, was ich dort ausprobiert habe. Ich weiß, daß das möglich ist, weil ich hier Screenshots von Dir selbst gesehen habe: https://github.com/wernerjoss/grav-plugin-fullcalendar/issues/44
- Die Endzeit ("bis 22:00") darzustellen unterstützt Dein Plugin wahrscheinlich nicht. Zumindest habe ich nichts darüber gefunden
- die Beschreibung des Events ist im Tooltip zu sehen. Wahrscheinlich gibt es auch keine Möglichkeit, die Beschreibung in einem eigenen Fenster z.B. nach Rechtsklick anzeigen zu lassen. Das ist aber nicht soo wichtig
- mir ist bewußt, daß die Tage des Monats so dargestellt werden, daß der zur Verfügung stehende Platz im Fenster gut ausgenutzt wird. Ich hätte gern, daß man die Höhe der Rechtecke (bzw. Quadrate), die einen Tag darstellen, begrenzen könnte. Auch hierzu habe ich in der Pluginbeschreibung und den Settings nichts gefunden, was das ermöglichen würde, und vermute deshalb, daß das nicht vorgesehen ist

Falls Du einen oder mehrere der Punkte mit wenig Aufwand kommentieren kannst bzw. mir sagen kannst, wo ich Informationen finde, wäre ich Dir sehr verbunden.

BTW: schönes Motorrad, Deine Yamaha!

Viele Grüße

Michael

**Comment by wernerjoss** [comment]
servus Michael,
meine Anmerkungen inline:

Am Montag, 27. März 2023, 19:17:59 CEST schrieb Racketsportler:
> @wernerjoss : Hallo Werner
> 
> Erstmal vielen Dank für die schnelle Antwort - ich hatte eher angenommen,
> daß ich ein paar Tage warten werde. Sehr nett! Das war jetzt leider
> Vorführeffekt. Ich habe drei Browser auf meiner Kiste - und im Chrome hat
> ein Strg-F5 nicht dazu geführt, daß die Umlaute richtig dargestellt werden.
> Der Firefox zeigt es tatsächlich korrekt an. Ich habe nicht damit
> gerechnet, daß der Chrome so hartnäckig dabei bleibt.

ja, das hab ich mir gedacht :-)

> Die Monatsbilder sind eher Spielerei. Ich wollte es ausprobieren, und fand
> die Bilder schön. Sieht wirklich wie ein echter Kalender aus.

genau das war das Ziel...

> Ich weiß, ich sollte keine Abkürzungen nehmen, sondern erstmal alles an
> Doku, FAQs, Known Bugs etc. wälzen. Vieles habe ich schon gelesen. Aber ich
> frage einfach mal - wenn etwas aufwändig zu recherchieren / auszuprobieren,
> aber lösbar sein sollte, werde ich es schon finden.
> 
> Was ich noch erreichen möchte ist:
> - bei den Events sollte die Anfangszeit im 24-Stundenformat dargestellt
> werden, also z.B. "13:00" - statt "1p". Der richtige Ort für die
> Einstellung wird wahrscheinlich die site.yaml ("dateformat") oder die
> system.yaml sein. Leider hat es keinen Effekt, was ich dort ausprobiert
> habe. Ich weiß, daß das möglich ist, weil ich hier Screenshots von Dir
> selbst gesehen habe:
> https://github.com/wernerjoss/grav-plugin-fullcalendar/issues/44 - 

dein Kalender ist englisch.
stell mal die Sprache auf deutsch, dann gehts.

> Die
> Endzeit ("bis 22:00") darzustellen unterstützt Dein Plugin wahrscheinlich
> nicht. Zumindest habe ich nichts darüber gefunden - die Beschreibung des
> Events ist im Tooltip zu sehen. Wahrscheinlich gibt es auch keine
> Möglichkeit, die Beschreibung in einem eigenen Fenster z.B. nach
> Rechtsklick anzeigen zu lassen. 

doch das geht:
enable onClick Popup for Event Description auf Enabled setzen

> Das ist aber nicht soo wichtig - mir ist
> bewußt, daß die Tage des Monats so dargestellt werden, daß der zur
> Verfügung stehende Platz im Fenster gut ausgenutzt wird. Ich hätte gern,
> daß man die Höhe der Rechtecke (bzw. Quadrate), die einen Tag darstellen,
> begrenzen könnte. Auch hierzu habe ich in der Pluginbeschreibung und den
> Settings nichts gefunden, was das ermöglichen würde, und vermute deshalb,
> daß das nicht vorgesehen ist

nein, das ist nicht vorgesehen.
das musst du im custom.css von deinem Theme machen.

> Falls Du einen oder mehrere der Punkte mit wenig Aufwand kommentieren kannst
> bzw. mir sagen kannst, wo ich Informationen finde, wäre ich Dir sehr
> verbunden.
> 
> BTW: schönes Motorrad, Deine Yamaha!

das ist nicht meine - meine eigenen Motorräder sind nicht so schön, nur 
schnell :-)
Gruss
Werner
P.S.: wenn dir das Plugin gefällt, kannst ihm einen Stern geben ;-)

**Comment by Racketsportler** [comment]
> wenn dir das Plugin gefällt, kannst ihm einen Stern geben ;-)

Habe ich gemacht. Ich vermute, Du meinst bei Github.
Sorry: ich habe mich erst vorgestern bei Github angemeldet, und bin noch nicht so bewandert.

> das ist nicht meine - meine eigenen Motorräder sind nicht so schön, nur schnell :-)

Alles gut: wenn es das ist, was Dir Freude bereitet ;-)

Ich kann mit allen Tipps etwas anfangen.
Leider ist ein Problem hartnäckig. Ich vermute auch, daß Du nicht viel dagegen machen kannst:

> > Was ich noch erreichen möchte ist: - bei den Events sollte die Anfangszeit im 24-Stundenformat dargestellt werden, also z.B. "13:00" - statt "1p". Der richtige Ort für die Einstellung wird wahrscheinlich die site.yaml ("dateformat") oder die system.yaml sein. Leider hat es keinen Effekt, was ich dort ausprobiert habe. Ich weiß, daß das möglich ist, weil ich hier Screenshots von Dir selbst gesehen habe: https://github.com/wernerjoss/grav-plugin-fullcalendar/issues/44

> dein Kalender ist englisch. stell mal die Sprache auf deutsch, dann gehts.

Der Kalender ist korrekt eingestellt, aber ich verstehe, was Du meinst:
![image](https://user-images.githubusercontent.com/129074153/228482742-0d3dc1c4-6b49-4586-89aa-e600d75d6e6b.png)

Wenn ich die Datei über den Link herunterlade, sehen die ersten Zeilen ("Header") folgendermaßen aus:

> BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:Termine TCH
X-WR-TIMEZONE:Europe/Berlin

Ich vermute, daß es um das "EN" in der zweiten Zeile geht.
In den jeweiligen Events finde ich nichts zu Zeitformaten:

> BEGIN:VEVENT
DTSTART:20230430T113000Z
DTEND:20230430T210000Z
DTSTAMP:20230329T084703Z
UID:56l20ffv8jhn7meof4uo5v40ra@google.com
CREATED:20230327T104249Z
DESCRIPTION:Zu Beginn der Freiluftsaison laden wir in jedem Jahr unsere Mit
 glieder ein\, um die ersten Spiele draußen zu spielen. Die Freigabe der Plä
 tze erfolgt in der Regel schon einige Tage oder sogar Wochen vorher.\n\nAuc
 h Besucher\, die nicht Mitglied in unserem Verein sind\, sind herzlich will
 kommen und dürfen sich an diesem Tag kostenfrei im weißen Sport probieren.
LAST-MODIFIED:20230327T200312Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:Saisoneröffnung mit Mixed-Turnier
TRANSP:OPAQUE
END:VEVENT

Was ich noch ausprobiert habe:
- ich habe die heruntergeladene Datei modifiziert - zweite Zeile endet auf "DE" - unter user/data/calendars gespeichert und nun diese Datei referenziert. Jetzt wird der Inhalt der Datei angezeigt, aber eben immer noch mit Uhrzeiten der Art "1p". Ehrlich gesagt kann ich mir auch nicht vorstellen, daß das die richtige Stelle ist, denn das EN ist ein Kürzel für eine Sprache, vielleicht noch für eine Location, aber eher nicht für ein Zeitformat
- ich habe im Google-Konto für die Kalender mal andere Einstellungen probiert - Italien / Italienisch / 1p und Kanada / Englisch / 1p - aber das ändert nichts an der Darstellung im Plugin: das bleibt hartnäckig bei "1p"

Falls Du noch eine Idee hast:
- was ich im Google-Konto noch anders einstellen könnte
- was ich in meinen Grav-Settings anders einstellen könnte

um das Gewünschte zu erreichen, wäre ich Dir sehr dankbar.

Ansonsten wünsche ich Dir schon mal viel Spaß mit Deinen Hobeln in der schönsten Zeit des Jahres fürs Mopedfahren - dem Frühling.

Viele Grüße

Michael

**Comment by wernerjoss** [comment]
moin Michael,

Am Mittwoch, 29. März 2023, 11:15:36 CEST schrieb Racketsportler:
> > wenn dir das Plugin gefällt, kannst ihm einen Stern geben ;-)
> 
> Habe ich gemacht. Ich vermute, Du meinst bei Github.
> Sorry: ich habe mich erst vorgestern bei Github angemeldet, und bin noch
> nicht so bewandert.

kein Problem - danke :-)

> > das ist nicht meine - meine eigenen Motorräder sind nicht so schön, nur
> > schnell :-)
> Alles gut: wenn es das ist, was Dir Freude bereitet ;-)
> 
> Ich kann mit allen Tipps etwas anfangen.
> 
> Leider ist ein Problem hartnäckig. Ich vermute auch, daß Du nicht viel dagegen machen 
kannst:

doch:
ich hatte mich nur etwas unklar ausgedrückt, mit 'Kalender auf deutsch einstellen'.
Damit ist gemeint, die Sprache im sog. Frontmatter der Kalenderseite,
der Eintrag 'lang: de' - siehe Screenshot:

![grafik](https://user-images.githubusercontent.com/36265757/228491753-132a513e-b869-4b40-ac1c-35c4810d45ed.png)
[1]
- das ist nicht sonderlich logisch,ja, aber eben eine Eigenschaft die vom verwendeten 
Kalender-Package fullcalendar.io vorgegeben wird.

> Ansonsten wünsche ich Dir schon mal viel Spaß mit Deinen Hobeln in der
> schönsten Zeit des Jahres fürs Mopedfahren - dem Frühling.

ja, ich hoffe, der kommt demnächst mal wirklich.
Gruss
Werner
Nachtrag: nach der Sprachumstellung müssen die Monatsbilder umbenannt werden (deutsche Monatsnamen)


--------
[1] Bild

**Comment by Racketsportler** [comment]
Hallo Werner

So: letzter "Nerver" von mir. Mit Deinen Tips kann ich nun der Homepage meines Tennisvereins einen Kalender hinzufügen, mit dem meine Kollegen wissen, wann welche Spiele und Turniere stattfinden.

>> Leider ist ein Problem hartnäckig. Ich vermute auch, daß Du nicht viel dagegen machen kannst

> doch: ich hatte mich nur etwas unklar ausgedrückt, mit 'Kalender auf deutsch einstellen'. Damit ist gemeint, die Sprache im sog. Frontmatter der Kalenderseite, der Eintrag 'lang: de' ... das ist nicht sonderlich logisch, ja, aber eben eine Eigenschaft die vom verwendeten Kalender-Package fullcalendar.io vorgegeben wird.

Habe ich verstanden und so eingestellt. So funktioniert es und gefällt mir sehr gut; vielen Dank!

> Nachtrag: nach der Sprachumstellung müssen die Monatsbilder umbenannt werden (deutsche Monatsnamen)

Das funktioniert beim einzigen Monat mit Umlaut im deutschen Namen - März - nicht. Egal ob ich die Datei "März.jpg" oder "Maerz.jpg" nenne: das Bild wird nicht verwendet. Bei allen anderen Monaten klappt alles.
Muß ich die Datei vielleicht "M& auml;rz.jpg" nennen - wenn das überhaupt geht?

Das ist nicht missionskritisch: vielleicht lasse ich die Bilder auch weg; da bin ich mir noch nicht sicher.

Viele Grüße

Michael

**Comment by wernerjoss** [comment]
servus Michael,
ändere mal in der Datei assest/monthpic.js ganz vorn die Variable debug auf true.
dann schau mal was in der Browser Konsole steht.
sollte so aussehen:
![grafik](https://user-images.githubusercontent.com/36265757/229165031-15ac25e7-3e7b-4576-b9f1-86db9a4fb751.png)
- wenn nicht, stimmt was mit deiner Systemeinstellung (locale) nicht.

**Comment by Racketsportler** [comment]
Hallo Werner
Das hat geholfen: danke. Auf Deinen Tipp hin habe ich die Datei von "März.jpg" in "M%C3%A4rz.jpg" umbenannt. Jetzt funktioniert es korrekt.
Eines der unzähligen Beispiele von UTF-8-Problemen, die es besser nicht geben sollte ...

**Comment by wernerjoss** [comment]
Am Sonntag, 2. April 2023, 11:31:56 CEST schrieb Racketsportler:
> Hallo Werner
> Das hat geholfen: danke. Auf Deinen Tipp hin habe ich die Datei von
> "März.jpg" in "M%C3%A4rz.jpg" umbenannt. Jetzt funktioniert es korrekt.
> Eines der unzähligen Beispiele von UTF-8-Problemen, die es besser nicht
> geben sollte ...

Moin Michael,
schön dass es jetzt klappt, wenn auch auf Umwegen :-)
und nochwas: in der Konsole auf deiner Webseite sind jede Menge javascript Fehler:

[1]
![grafik](https://user-images.githubusercontent.com/36265757/229345075-ad09ab5d-acdf-472a-bc01-65204013d05a.png)


irgendwas stimmt da mit deinem Theme nicht (braucht ggf. älteres jquery).
Gruss
Werner



--------
[1] Bild
