### ISSUE TITLE
I can't get events to display

### ISSUE THREAD

**Issue by ventoux84** [wernerjoss/grav-plugin-fullcalendar#54]
Hello,
After installing the plugin, activating it and creating a "calendar" page with  page template = calendar,  i can't get events to display. I used the admin plugin for that.
I placed the .ics file in /user/data/calendars and added in the page's content [fullcalendar icsfile="nom.ics"][/fullcalendar]
I tried with an other ics file, but it's the same thing : no event.
The page displays the calendar widget, but all dates are empty. No event is displayed, even there is one every days.

I also tried with the url of my Nextcloud calendar.
https://my-domain/cloud/remote.php/dav/calendars/my-account/personnel-1/

Could you please tell me what i'm forgetting ?
Grav and plugins are up to date.

**Comment by ventoux84** [comment]
It works, only with the ics file in the page's directory and  :
[fullcalendar][/fullcalendar]

Now i'm looking for adding images. They are in the page's directory with month names , what else to do ? Something in the content area ? Or only with template = default and fullcalendar: true ? But this way, no event displayed.

**Comment by wernerjoss** [comment]
> Hello, After installing the plugin, activating it and creating a "calendar" page with page template = calendar, i can't get events to display. I used the admin plugin for that. I placed the .ics file in /user/data/calendars and added in the page's content [fullcalendar icsfile="nom.ics"][/fullcalendar] I tried with an other ics file, but it's the same thing : no event. The page displays the calendar widget, but all dates are empty. No event is displayed, even there is one every days.
> 

that is the correct procedure, which should normally work (I use it the same way for my own calendar page)

> I also tried with the url of my Nextcloud calendar. https://my-domain/cloud/remote.php/dav/calendars/my-account/personnel-1/

this will probably not work, unless the link points directly to an .ics file

> 
> Could you please tell me what i'm forgetting ? Grav and plugins are up to date.

you could set verbose=true in Line 17 in file assets/calendar.js and then look what is displayed in the javascript console of your browser.

**Comment by wernerjoss** [comment]
> It works, only with the ics file in the page's directory and : [fullcalendar][/fullcalendar]

right, this is the 2nd supported way to add ics files for fullcalendar.

> Now i'm looking for adding images. They are in the page's directory with month names , what else to do ? 

Month names should be named in the language your site uses, e.g. Octobre.jpg for french, Oktober.jpg for german
plus, there must be exactly one for each month.
again, there is a variable debug in monthpic.js which can be set to true for investigation.


> Something in the content area ? Or only with template = default and fullcalendar: true ? But this way, no event displayed.

that is true, it only works with template=calendar.html.twig
(=page file must be named calendar.md)

**Comment by ventoux84** [comment]
Thanks for that.
To sum up :
I create new page in admin plugin with template "calendar", put the ics file in its directory and a short code without path in the content. These works and events are displayed.

Then i add the 12 images in the page's content with the good name for each. None image displayed. I'll check the debug mode.

The readme.md says :
> In short, the use of the Default page template is recommended for most use cases, as only this way, you will be able to use the monthly picture feature or the handy calendar page drop-in for ics files.

I understand that the page's template must not be "calendar" but "default" if i want to display images.

EDIT : I got the images ! In french, no capital letter in month's name !!! Also, no .JPG, but .jpg !!!

**Comment by wernerjoss** [comment]
> The readme.md says :
> 
> > In short, the use of the Default page template is recommended for most use cases, as only this way, you will be able to use the monthly picture feature or the handy calendar page drop-in for ics files.
> 
> I understand that the page's template must not be "calendar" but "default" if i want to display images.

no, I guess I'll try to clarify the docs: the Default Page Template in the docs really means calendar.html.twig, NOT
default.html.twig.
sorry for the confusion.

> EDIT : I got the images ! In french, no capital letter in month's name !!! Also, no .JPG, but .jpg !!!

Ok, I did not check capital letters in french (frankly, I never tried french as site language), but ,yes .jpg IS required, NOT .JPG

so, I guess, it is now working for you, right ?

**Comment by ventoux84** [comment]
Yes all right with the shortcode without url and the ics file in the page's directory.

Does not work with the shortcode with url, in this site or the private link for my Nextcloud agenda.  

I thank you very much for yours comments and this plugin.

**Comment by wernerjoss** [comment]
ok, thanks for feedback.
but, still strange the shortcode with ics file name does not work for you.
did you enable verbose=true in calendar.js and check what is printed in javascript console ?
(there you should see which calendar files are searched, and, if not found, probably why)

**Comment by ventoux84** [comment]
> did you enable verbose=true in calendar.js and check what is printed in javascript console ?

Yes, but i can't find the javascript console window.
There is a lot of errors and it's too difficult for me. Sorry

Also, i tried with an other web browser, no change.

**Comment by wernerjoss** [comment]
ok, if you are on Windows, hit F12, that will get you to the debug window of your browser, from there, you can go to the console tab, that should look like this:

![grafik](https://github.com/wernerjoss/grav-plugin-fullcalendar/assets/36265757/fd6deacb-91d8-42b7-a9a4-7eac250e36a1)

(cfgfiles is the array which holds the .ics file names from the shortcode)

**Comment by wernerjoss** [comment]
...btw. your nick and avatar remind me of the mont ventoux, right ?
(I've been there several times, very nice place !)

**Comment by ventoux84** [comment]
> remind me of the mont ventoux, right ?

Yes, i live in a village at the Mont Ventoux's foot. And not so far from Ledenon ! 

Tomarrow, i start one week's vacation. Then, i will try again the console of Firefox on my Archlinux PC.  

I started this small site for a friend who rents a studio in my village.
https://mazanette.fr/fr

Best regards

**Comment by wernerjoss** [comment]
ok, fine :smile: 
btw. the Circuit of Ledenon is stil (by far) my favourite Motorbike Race Track, see the [Report of our last event there](https://hoernerfranzracing.de/werner/blog/ledenon-2010-fast-live).
so, happy vacation for now.

**Comment by ventoux84** [comment]
I tested in an other site that i'm building.
It works fine with the shortcode`
[fullcalendar icsfile="nom.ics"][/fullcalendar]` and the ics file in the calendars directory.

Tomarrow i will test with an url of an external calendar.

**Comment by ventoux84** [comment]
I got a 404 in the console.
Solved with switching to "no" the parameter "Inclure la langue par défaut dans l'extension de fichier "

**Comment by wernerjoss** [comment]
ok, fine to see you got this solved :smile:  - maybe I'll add a hint to the docs w.r. file name extension.
btw., if you like this plugin, you can give it a star :grinning:
