### ISSUE TITLE
How to pass options to Calendar?

### ISSUE THREAD

**Issue by envas** [wernerjoss/grav-plugin-fullcalendar#57]
I need to change the cell height. In Fullcalendar.io, I can do it by passing either the aspect ratio or countentHeight option to the constructor. So, for this plugin, I updated [calendar.js](https://github.com/wernerjoss/grav-plugin-fullcalendar/blob/101777afc8075f4c9977a6d027dfc9cb7aa779ce/assets/calendar.js#L209). It works, but it probably is not the best way because it is not 'update resistant'. 

Is there a better way how to add the Calendar option?

**Comment by wernerjoss** [comment]
@envas : I'm not sure what you mean with 'I updated calendar.js' - I guess you changed calendars.js so you can pass cell height, right ?
and, if so, you would also need to change templates/partials/fullcalendar.html.twig.
so, yes, currently only the options present in fullcalendar.html.twig are intended to be configurable, not all the (many) other options that are possible in fullcalendar.io

**Comment by envas** [comment]
You are right. I am passing an additional hardcoded option for the `aspectRatio` to the FullCalendar constructor like this. 
```
	var calendar = new FullCalendar.Calendar(calendarEl, {
		plugins: [ 'interaction', 'dayGrid', 'rrule', 'moment', 'momentTimezone' ],	// docs on plugin names are wrong !!
		timeZone: calTimezone,	//	setting from config, default is 'local'
		locale: LocaleCode,
		weekNumbers: weekNums,
		aspectRatio: 3,
		header: {
			left: 'prevYear,nextYear',
			center: 'title',
		},
                 . . .
```
However, the changes (may) disappear on the next update, so the question was if there is another way. Anyway, thank you for a nice plugin.

**Comment by wernerjoss** [comment]
ok, just for the record: I'm currently not planning any updates, but rather think about a complete rewrite, based on fullcalendar.io V 6.x, but that will not happen in the near future.
