### ISSUE TITLE
Google Calendar .ics Support

### ISSUE THREAD

**Issue by flo-bananzki** [wernerjoss/grav-plugin-fullcalendar#6]
Hello Werner,
I wonder if the plugin already has Google Calendar Support?
And if, where do I need to set my API Key and Calendar ID?
I get the JSON Strings of my public Google Calendar in the Console but my Browser restricts it with an CORS Header Failure. (Reason: CORS-Header 'Access-Control-Allow-Origin' is Missing)
If you have any expirience with this issue, I would appreciate your Help.
Thanks, Flo

**Comment by flo-bananzki** [comment]
Looks like I dont need an API Key and ID.
To get around the CORS Failure I used the CORS Anywhere reverse proxy by [Rob--W](https://github.com/Rob--W) 
[This is the Setup from sideshowbaker on stackoverflow](https://stackoverflow.com/questions/43871637/no-access-control-allow-origin-header-is-present-on-the-requested-resource-whe/43881141#43881141)

**Comment by wernerjoss** [comment]
Ok, fine you found a workaround.
of course, the easiest way would be to enable CORS on the server where reomte ics files are stored.
for this, however, you need admin access to that server which usually is not available.

**Comment by FabianClemenz** [comment]
@flo-bananzki did you differ the js code of the plugin to use the Proxy or did you create some boilerplate Javascript which adds this to all responses?

**Comment by flo-bananzki** [comment]
@FreakyTea there is no need to change the Code of this Plugin.
I set up an Reverse Proxy on Heroku like described in the link of my last post. (You can try it with the provided test Proxy first) Then you just put the new URL in the fullcalendar shortcode like this:
```
[fullcalendar icsfile="https://cors-anywhere.herokuapp.com/https://calendar.google.com/calendar/ical/myname%40myorganization.com/public/basic.ics" ][/fullcalendar]
```
It just Passes that response, with injects an (`Access-Control-Allow-Origin: *`) header into the response the browser sees.

**Comment by wernerjoss** [comment]
@flo-bananzki , thats a good hint for those who are hit by CORS issues.
I'll reference this in the docs.

**Comment by FabianClemenz** [comment]
@flo-bananzki Thanks for the help, didn't understand the stackoverflow post^^ my customer will have to think about if they want a proxy or just download the ics file

**Comment by flo-bananzki** [comment]
Thanks. I think we can close this Issue, cause its not related to the Code of the Plugin.

**Comment by rocifier** [comment]
Is there any way to make the fetch a "simple request" so that the browser doesn't do the CORS check? We are just fetching plain text, I would have thought it was possible for the plugin to download that with a no-cors mode instead of having to build reverse proxies just to use this feature

**Comment by wernerjoss** [comment]
Am Mittwoch, 7. Juli 2021, 08:11:14 CEST schrieb rocifier:
> Is there any way to make the fetch a "simple request" so that the browser
> doesn't do the CORS check? We are just fetching plain text, I would have
> thought it was possible for the plugin to download that with a no-cors mode
> instead of having to build reverse proxies just to use this feature

no, this plugin is written in javascript and thus always triggers the 
browser's CORS check, regardless of the data type beeing requested.
you could write a small php script which copies the text file to your local 
site via cron job and then access this without CORS.
