### ISSUE TITLE
Google calendar

### ISSUE THREAD

**Issue by fugo** [wernerjoss/grav-plugin-fullcalendar#9]
I installed today Grav plus your calendar plugin but I get only an empty calendar.  
Grav v1.6.19 - Admin v1.9.12 -  FullCalendar v0.1.4  
Its a test site @ https://tim-hs.site/ths/en/sample-page  
It should show 2 events @18/12/2019 whole day **test** and @19/12/2019 @10:00 **nochn test**

shortcode core v4.1.7 installed

Is Google calendar not working? Or what I did wrong? 
@ https://tim-hs.site/ths/de/sample-page I also tried the google *iframe* that shows me the events.

**Comment by wernerjoss** [comment]
I think this is not a google calendar problem but a CORS issue, I tried your ical link here and get in developer console:
`Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://calendar.google.com/calendar/ical/gnote612%40gmail.com/private-697d8ac35bb2a0fc0ef7777640b426b7/basic.ics. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt)`

see also [this issue](https://github.com/wernerjoss/grav-plugin-fullcalendar/issues/6)

**Comment by fugo** [comment]
I tried the ``https://cors-anywhere.herokuapp.com`` could be at that moment it was down.
Today it works and after the new update the JS error is also away.
So I need to setup a Proxy for google calendar? 

But for me the main problem is like #8 no repeating events. 

So at the moment I had to live with that ugly google iframe implementation

**Comment by wernerjoss** [comment]
@fugo : see my comment on [#8](https://github.com/wernerjoss/grav-plugin-fullcalendar/issues/8)
